export type CreateAudienceOutput = {
  id: string;
  name: string;
  email: string;
  nickname: string | null;
  avatar: string | null;
  phone: string | null;
  favorite_genres: string[];
  favorite_instruments: string[];
  total_points: number;
  current_level: number;
  badges: string[];
  total_scans: number;
  total_requests: number;
  total_tips: number;
  total_social_shares: number;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
};
