import { ConfigService } from "@nestjs/config";

export const CONFIG_SCHEMA_TYPE = Symbol("CONFIG_SCHEMA_TYPE");

export type EnvConfig = {
  NODE_ENV: "development" | "production" | "test";
  PORT: number;
  APP_URL: string;

  SWAGGER_EXAMPLES_ENABLED?: boolean;
  SWAGGER_EXAMPLES_REQUIRED_ONLY?: boolean;

  // Database URLs
  DATABASE_URL: string;
  MONGODB_URL?: string;
  REDIS_URL: string;

  // RabbitMQ
  RABBITMQ_URL: string;
  RABBITMQ_EXCHANGE: string;
  RABBITMQ_QUEUE_REQUESTS: string;
  RABBITMQ_QUEUE_NOTIFICATIONS: string;
  RABBITMQ_QUEUE_PAYMENTS: string;
  RABBITMQ_QUEUE_GAMIFICATION: string;
  RABBITMQ_REGISTER_HANDLERS?: boolean;

  RABBITMQ_ROUTING_KEY_AI_AUDIO_UPLOAD_VALIDATED?: string;
  RABBITMQ_ROUTING_KEY_AI_AUDIO_UPLOAD_SEPARATED?: string;
  RABBITMQ_ROUTING_KEY_AI_AUDIO_UPLOAD_SEPARATION_FAILED?: string;
  RABBITMQ_QUEUE_AI_AUDIO_SEPARATION?: string;
  RABBITMQ_QUEUE_AI_AUDIO_SEPARATION_COMPLETED?: string;
  RABBITMQ_QUEUE_AI_AUDIO_SEPARATION_FAILED?: string;

  // Keycloak
  AUTH_JWT_VALIDATION_MODE?: "local" | "keycloak";
  KEYCLOAK_URL: string;
  KEYCLOAK_REALM: string;
  KEYCLOAK_CLIENT_ID: string;
  KEYCLOAK_CLIENT_SECRET: string;
  KEYCLOAK_JWKS_URI?: string;
  KEYCLOAK_JWKS_CACHE_TTL_SECONDS?: number;
  KEYCLOAK_VERIFY_AUDIENCE?: boolean;

  // JWT
  JWT_SECRET: string;
  JWT_EXPIRES_IN: string;
  JWT_REFRESH_SECRET: string;
  JWT_REFRESH_EXPIRES_IN: string;

  // AWS S3
  AWS_REGION: string;
  AWS_ACCESS_KEY_ID?: string;
  AWS_SECRET_ACCESS_KEY?: string;
  AWS_S3_BUCKET: string;
  AWS_CLOUDFRONT_URL?: string;

  // MinIO (Development)
  MINIO_ENDPOINT: string;
  MINIO_PORT: number;
  MINIO_ACCESS_KEY: string;
  MINIO_SECRET_KEY: string;
  MINIO_BUCKET: string;

  MINIO_PUBLIC_ENDPOINT?: string;
  MINIO_PUBLIC_PORT?: number;

  CLOUDFLARE_R2_ENDPOINT?: string;
  CLOUDFLARE_R2_ACCESS_KEY_ID?: string;
  CLOUDFLARE_R2_SECRET_ACCESS_KEY?: string;
  CLOUDFLARE_R2_BUCKET?: string;

  // AI Audio
  AI_AUDIO_STORAGE_PROVIDER?: "minio" | "aws_s3" | "cloudflare_r2";
  AI_AUDIO_SEPARATION_HTTP_BASE_URL?: string;
  AI_AUDIO_SEPARATION_HTTP_PATH?: string;
  AI_AUDIO_SEPARATION_HTTP_TIMEOUT_MS?: number;
  AI_AUDIO_PROCESSING_TRANSPORT?: "http" | "rabbitmq";
  AI_AUDIO_PROCESSING_CONCURRENCY?: number;
  AI_AUDIO_PROCESSING_MAX_QUEUE_SIZE?: number;
  AI_AUDIO_PROCESSING_BACKPRESSURE_ENQUEUE_DELAY_MS?: number;
  AI_AUDIO_PROCESSING_BACKPRESSURE_TICK_MS?: number;
  AI_AUDIO_PROCESSING_MAX_RSS_MB?: number | null;
  AI_AUDIO_PROCESSING_MAX_LOADAVG_1?: number | null;
  AI_AUDIO_PROCESSING_GPU_MAX_MEMORY_PERCENT?: number | null;
  AI_AUDIO_PROCESSING_GPU_CHECK_INTERVAL_MS?: number;
  AI_AUDIO_MAX_FILE_SIZE?: number;
  AI_AUDIO_ALLOWED_MIME_TYPES?: string;
  AI_AUDIO_DEFAULT_MODEL_ID?: string;
  AI_AUDIO_PROGRESS_TOKEN?: string;

  RABBITMQ_ROUTING_KEY_AI_CIFRA_ANALYSIS_REQUESTED?: string;
  RABBITMQ_ROUTING_KEY_AI_CIFRA_ANALYSIS_COMPLETED?: string;
  RABBITMQ_ROUTING_KEY_AI_CIFRA_ANALYSIS_FAILED?: string;
  RABBITMQ_ROUTING_KEY_AI_CIFRA_ANALYSIS_PROGRESS?: string;
  RABBITMQ_QUEUE_AI_CIFRA_ANALYSIS?: string;
  RABBITMQ_QUEUE_AI_CIFRA_ANALYSIS_COMPLETED?: string;
  RABBITMQ_QUEUE_AI_CIFRA_ANALYSIS_FAILED?: string;
  RABBITMQ_QUEUE_AI_CIFRA_ANALYSIS_PROGRESS?: string;

  RABBITMQ_ROUTING_KEY_SYNCED_LYRICS_BULK_REQUESTED?: string;
  RABBITMQ_QUEUE_SYNCED_LYRICS_BULK?: string;

  // AI Cifra
  AI_CIFRA_STORAGE_PROVIDER?: "minio" | "aws_s3" | "cloudflare_r2";
  AI_CIFRA_ANALYSIS_HTTP_BASE_URL?: string;
  AI_CIFRA_ANALYSIS_HTTP_PATH?: string;
  AI_CIFRA_ANALYSIS_HTTP_TIMEOUT_MS?: number;
  AI_CIFRA_PROCESSING_TRANSPORT?: "http" | "rabbitmq";
  AI_CIFRA_PROCESSING_CONCURRENCY?: number;
  AI_CIFRA_PROCESSING_MAX_QUEUE_SIZE?: number;
  AI_CIFRA_PROCESSING_BACKPRESSURE_ENQUEUE_DELAY_MS?: number;
  AI_CIFRA_PROCESSING_BACKPRESSURE_TICK_MS?: number;
  AI_CIFRA_PROCESSING_MAX_RSS_MB?: number | null;
  AI_CIFRA_PROCESSING_MAX_LOADAVG_1?: number | null;
  AI_CIFRA_PROCESSING_GPU_MAX_MEMORY_PERCENT?: number | null;
  AI_CIFRA_PROCESSING_GPU_CHECK_INTERVAL_MS?: number;
  AI_CIFRA_MAX_FILE_SIZE?: number;
  AI_CIFRA_ALLOWED_MIME_TYPES?: string;
  AI_CIFRA_DEFAULT_MODEL_ID?: string;
  AI_CIFRA_PROGRESS_TOKEN?: string;
  AI_CIFRA_AUDIO_TTL_MINUTES?: number;
  AI_CIFRA_SIMPMUSIC_YTDLP_BIN?: string;
  AI_CIFRA_SIMPMUSIC_YTDLP_TIMEOUT_MS?: number;
  AI_CIFRA_MUSIFY_PIPED_BASE_URL?: string;
  AI_CIFRA_MUSIFY_PIPED_TIMEOUT_MS?: number;

  // External APIs
  CIFRA_CLUB_API_KEY?: string;
  ULTIMATE_GUITAR_API_KEY?: string;
  SPOTIFY_CLIENT_ID?: string;
  SPOTIFY_CLIENT_SECRET?: string;
  GENIUS_CLIENT_ID?: string;
  GENIUS_CLIENT_SECRET?: string;
  GENIUS_ACCESS_TOKEN?: string;

  // Synced Lyrics
  SYNCED_LYRICS_BULK_TRANSPORT?: "inline" | "rabbitmq";
  SYNCED_LYRICS_BULK_CONCURRENCY?: number;
  SYNCED_LYRICS_BULK_MAX_QUEUE_SIZE?: number;
  SYNCED_LYRICS_BULK_BACKPRESSURE_ENQUEUE_DELAY_MS?: number;
  SYNCED_LYRICS_BULK_BACKPRESSURE_TICK_MS?: number;
  SYNCED_LYRICS_BULK_TOKEN?: string;

  // Asaas — cachê de show, escrow, assinaturas, saque PIX
  ASAAS_API_URL: string;
  ASAAS_API_KEY?: string;
  ASAAS_WALLET_ID?: string;
  ASAAS_WEBHOOK_TOKEN?: string;

  // Iugu — gorjetas PIX
  IUGU_API_URL: string;
  IUGU_API_TOKEN?: string;
  IUGU_ACCOUNT_ID?: string;
  IUGU_WEBHOOK_TOKEN?: string;

  // Push Notifications
  FIREBASE_PROJECT_ID?: string;
  FIREBASE_PRIVATE_KEY?: string;
  FIREBASE_CLIENT_EMAIL?: string;
  FIREBASE_SERVICE_ACCOUNT_KEY?: string;

  // Email — Resend
  RESEND_API_KEY?: string;
  MAIL_FROM?: string;
  MAIL_BASE_URL?: string;

  // Rate Limiting
  RATE_LIMIT_TTL: number;
  RATE_LIMIT_MAX: number;

  // File Upload
  MAX_FILE_SIZE: number;
  ALLOWED_IMAGE_TYPES: string;
  ALLOWED_VIDEO_TYPES: string;
  ALLOWED_AUDIO_TYPES: string;

  // Gamification
  POINTS_SCAN_QR: number;
  POINTS_MUSIC_REQUEST: number;
  POINTS_REQUEST_ACCEPTED: number;
  POINTS_TIP_MULTIPLIER: number;
  POINTS_SOCIAL_SHARE: number;

  // Anti-Spam
  MAX_REQUESTS_PER_USER_PER_EVENT: number;
  REQUEST_COOLDOWN_MINUTES: number;
  REQUEST_RESPONSE_TIME_MINUTES: number;
  VOTING_INTERVAL_MINUTES: number;

  // Scheduling
  BOOKING_DEFAULT_FREE_CANCELLATION_HOURS: number;

  // Prisma
  PRISMA_LOG_QUERIES: boolean;
};

export type ConfigSchemaType = ConfigService<EnvConfig>;
