export type AudienceModel = {
  id: string;
  email: string;
  name: string;
  nickname: string | null;
  avatar: string | null;
  phone: string | null;
  points: number;
  monthly_points: number;
  level: number;
  last_points_update?: Date;
  badges: string[];
  favorite_genres: string[];
  favorite_artists: string[];
  favorite_instruments: string[];
  preferred_languages: string[];
  location: any;
  social_links: any;
  notification_settings: any;
  privacy_settings: any;
  discovery_settings: any;
  is_active: boolean;
  email_verified_at?: Date | null;
  email_pending?: string | null;
  email_token?: string | null;
  email_token_expires_at?: Date | null;
  created_at: Date;
  updated_at: Date;
};
