export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonObject | JsonArray;
export type JsonObject = { [key: string]: JsonValue | undefined };
export type JsonArray = JsonValue[];

export type MusicLibraryModel = {
  id: string;
  musicianId: string;
  title: string;
  artist: string;
  genre: string | null;
  key: string | null;
  bpm: number | null;
  lyrics: string | null;
  chords: JsonValue | null;
  structure_segments: JsonValue | null;
  chord_sheet: JsonValue | null;
  chord_sheet_version: number;
  renderable_chord_sheet: JsonValue | null;
  renderable_chord_sheet_version: number;
  notes: string | null;
  difficulty: number;
  isFavorite: boolean;
  source: string | null;
  sourceId: string | null;
  lrc_raw: string | null;
  lrc_normalized: JsonValue | null;
  lrc_provider: string | null;
  lrc_provider_meta: JsonValue | null;
  lrc_hash: string | null;
  lrc_version: number;
  lrc_pipeline_version: number;
  lrc_quality_flags: string[];
  lrc_coverage_ms: number | null;
  lrc_has_word_timestamps: boolean;
  lrc_last_synced_at: Date | null;
  duration_seconds: number | null;
  created_at: Date;
  updated_at: Date;
};
